vim.keymap.del("i", ",")
vim.keymap.del("i", ".")
vim.keymap.del("i", ";")
vim.keymap.del("x", "<")
vim.keymap.del("n", "<C-Down>")
vim.keymap.del("n", "<C-Left>")
vim.keymap.del("n", "<C-Right>")
vim.keymap.del("n", "<C-Up>")
vim.keymap.del("n", "<C-h>")
vim.keymap.del("n", "<C-j>")
vim.keymap.del("n", "<C-k>")
vim.keymap.del("n", "<C-l>")
vim.keymap.del({ "n", "i", "x", "s" }, "<C-s>")
vim.keymap.del({ "n", "x" }, "<Down>")
vim.keymap.del("n", "<S-h>")
vim.keymap.del("n", "<S-l>")
vim.keymap.del({ "n", "x" }, "<Up>")
vim.keymap.del({ "n", "t" }, "<c-/>")
vim.keymap.del({ "n", "t" }, "<c-_>")
vim.keymap.del({ "n", "i", "s" }, "<esc>")
vim.keymap.del("n", "<leader>-")
vim.keymap.del("n", "<leader><tab><tab>")
vim.keymap.del("n", "<leader><tab>[")
vim.keymap.del("n", "<leader><tab>]")
vim.keymap.del("n", "<leader><tab>d")
vim.keymap.del("n", "<leader><tab>f")
vim.keymap.del("n", "<leader><tab>l")
vim.keymap.del("n", "<leader><tab>o")
vim.keymap.del("n", "<leader>K")
vim.keymap.del("n", "<leader>L")
vim.keymap.del("n", "<leader>`")
vim.keymap.del("n", "<leader>bD")
-- vim.keymap.del("n", "<leader>bd")
vim.keymap.del("n", "<leader>bo")
vim.keymap.del("n", "<leader>cd")
vim.keymap.del({ "n", "x" }, "<leader>cf")
vim.keymap.del("n", "<leader>dph")
vim.keymap.del("n", "<leader>dpp")
vim.keymap.del("n", "<leader>fn")
-- vim.keymap.del("n", "<leader>ft")
vim.keymap.del("n", "<leader>fT")
vim.keymap.del({ "n", "x" }, "<leader>gB")
-- vim.keymap.del("n", "<leader>gG")
vim.keymap.del("n", "<leader>gL")
vim.keymap.del({ "n", "x" }, "<leader>gY")
vim.keymap.del("n", "<leader>gb")
vim.keymap.del("n", "<leader>gf")
-- vim.keymap.del("n", "<leader>gg")
vim.keymap.del("n", "<leader>gl")
vim.keymap.del("n", "<leader>l")
vim.keymap.del("n", "<leader>uA")
vim.keymap.del("n", "<leader>uD")
vim.keymap.del("n", "<leader>uF")
vim.keymap.del("n", "<leader>uI")
vim.keymap.del("n", "<leader>uL")
vim.keymap.del("n", "<leader>uS")
vim.keymap.del("n", "<leader>uT")
vim.keymap.del("n", "<leader>uZ")
vim.keymap.del("n", "<leader>ua")
vim.keymap.del("n", "<leader>ub")
vim.keymap.del("n", "<leader>uc")
vim.keymap.del("n", "<leader>ud")
vim.keymap.del("n", "<leader>uf")
vim.keymap.del("n", "<leader>ug")
vim.keymap.del("n", "<leader>uh")
vim.keymap.del("n", "<leader>ui")
vim.keymap.del("n", "<leader>ul")
vim.keymap.del("n", "<leader>ur")
vim.keymap.del("n", "<leader>us")
vim.keymap.del("n", "<leader>uw")
vim.keymap.del("n", "<leader>uz")
-- vim.keymap.del("n", "<leader>wd")
vim.keymap.del("n", "<leader>wm")
vim.keymap.del("n", "<leader>xl")
vim.keymap.del("n", "<leader>xq")
vim.keymap.del("n", "<leader>|")
-- vim.keymap.del({ "n", "x" }, "<localleader>r")
vim.keymap.del("x", ">")
vim.keymap.del({ "n", "x", "o" }, "N")
vim.keymap.del("n", "[b")
vim.keymap.del("n", "[d")
vim.keymap.del("n", "[e")
vim.keymap.del("n", "[q")
vim.keymap.del("n", "[w")
vim.keymap.del("n", "]b")
vim.keymap.del("n", "]d")
vim.keymap.del("n", "]e")
vim.keymap.del("n", "]q")
vim.keymap.del("n", "]w")
vim.keymap.del("n", "gcO")
vim.keymap.del("n", "gco")
vim.keymap.del({ "n", "x" }, "j")
vim.keymap.del({ "n", "x" }, "k")
vim.keymap.del({ "n", "x", "o" }, "n")
