Snacks.keymap.del("i", ",")
Snacks.keymap.del("i", ".")
Snacks.keymap.del("i", ";")
Snacks.keymap.del("x", "<")
Snacks.keymap.del("n", "<C-Down>")
Snacks.keymap.del("n", "<C-Left>")
Snacks.keymap.del("n", "<C-Right>")
Snacks.keymap.del("n", "<C-Up>")
Snacks.keymap.del("n", "<C-h>")
Snacks.keymap.del("n", "<C-j>")
Snacks.keymap.del("n", "<C-k>")
Snacks.keymap.del("n", "<C-l>")
Snacks.keymap.del({ "n", "i", "x", "s" }, "<C-s>")
Snacks.keymap.del({ "n", "x" }, "<Down>")
Snacks.keymap.del("n", "<S-h>")
Snacks.keymap.del("n", "<S-l>")
Snacks.keymap.del({ "n", "x" }, "<Up>")
Snacks.keymap.del({ "n", "t" }, "<c-/>")
Snacks.keymap.del({ "n", "t" }, "<c-_>")
Snacks.keymap.del({ "n", "i", "s" }, "<esc>")
Snacks.keymap.del("n", "<leader>-")
Snacks.keymap.del("n", "<leader><tab><tab>")
Snacks.keymap.del("n", "<leader><tab>[")
Snacks.keymap.del("n", "<leader><tab>]")
Snacks.keymap.del("n", "<leader><tab>d")
Snacks.keymap.del("n", "<leader><tab>f")
Snacks.keymap.del("n", "<leader><tab>l")
Snacks.keymap.del("n", "<leader><tab>o")
Snacks.keymap.del("n", "<leader>K")
Snacks.keymap.del("n", "<leader>L")
Snacks.keymap.del("n", "<leader>`")
Snacks.keymap.del("n", "<leader>bD")
Snacks.keymap.del("n", "<leader>bd")
Snacks.keymap.del("n", "<leader>bo")
Snacks.keymap.del("n", "<leader>cd")
Snacks.keymap.del({ "n", "x" }, "<leader>cf")
Snacks.keymap.del("n", "<leader>dph")
Snacks.keymap.del("n", "<leader>dpp")
Snacks.keymap.del("n", "<leader>fn")
Snacks.keymap.del("n", "<leader>ft")
Snacks.keymap.del("n", "<leader>fT")
Snacks.keymap.del({ "n", "x" }, "<leader>gB")
-- Snacks.keymap.del("n", "<leader>gG")
Snacks.keymap.del("n", "<leader>gL")
Snacks.keymap.del({ "n", "x" }, "<leader>gY")
Snacks.keymap.del("n", "<leader>gb")
Snacks.keymap.del("n", "<leader>gf")
-- Snacks.keymap.del("n", "<leader>gg")
Snacks.keymap.del("n", "<leader>gl")
Snacks.keymap.del("n", "<leader>l")
Snacks.keymap.del("n", "<leader>uA")
Snacks.keymap.del("n", "<leader>uD")
Snacks.keymap.del("n", "<leader>uF")
Snacks.keymap.del("n", "<leader>uI")
Snacks.keymap.del("n", "<leader>uL")
Snacks.keymap.del("n", "<leader>uS")
Snacks.keymap.del("n", "<leader>uT")
Snacks.keymap.del("n", "<leader>uZ")
Snacks.keymap.del("n", "<leader>ua")
Snacks.keymap.del("n", "<leader>ub")
Snacks.keymap.del("n", "<leader>uc")
Snacks.keymap.del("n", "<leader>ud")
Snacks.keymap.del("n", "<leader>uf")
Snacks.keymap.del("n", "<leader>ug")
Snacks.keymap.del("n", "<leader>uh")
Snacks.keymap.del("n", "<leader>ui")
Snacks.keymap.del("n", "<leader>ul")
Snacks.keymap.del("n", "<leader>ur")
Snacks.keymap.del("n", "<leader>us")
Snacks.keymap.del("n", "<leader>uw")
Snacks.keymap.del("n", "<leader>uz")
Snacks.keymap.del("n", "<leader>wd")
Snacks.keymap.del("n", "<leader>wm")
Snacks.keymap.del("n", "<leader>xl")
Snacks.keymap.del("n", "<leader>xq")
Snacks.keymap.del("n", "<leader>|")
-- Snacks.keymap.del({ "n", "x" }, "<localleader>r")
Snacks.keymap.del("x", ">")
Snacks.keymap.del({ "n", "x", "o" }, "N")
Snacks.keymap.del("n", "[b")
Snacks.keymap.del("n", "[d")
Snacks.keymap.del("n", "[e")
Snacks.keymap.del("n", "[q")
Snacks.keymap.del("n", "[w")
Snacks.keymap.del("n", "]b")
Snacks.keymap.del("n", "]d")
Snacks.keymap.del("n", "]e")
Snacks.keymap.del("n", "]q")
Snacks.keymap.del("n", "]w")
Snacks.keymap.del("n", "gcO")
Snacks.keymap.del("n", "gco")
Snacks.keymap.del({ "n", "x" }, "j")
Snacks.keymap.del({ "n", "x" }, "k")
Snacks.keymap.del({ "n", "x", "o" }, "n")

local function set_clipboard(text)
  if not text or text == "" then
    return
  end
  vim.fn.setreg("+", text)
  vim.fn.setreg("*", text)
  vim.fn.setreg('"', text)
end

local function filepath_with_line_abs()
  local bufname = vim.api.nvim_buf_get_name(0)
  if bufname == "" then
    return nil
  end
  local line = vim.api.nvim_win_get_cursor(0)[1]
  return string.format("%s:%d", bufname, line)
end

local function filepath_with_line_project()
  local bufname = vim.api.nvim_buf_get_name(0)
  if bufname == "" then
    return nil
  end

  local root = LazyVim.root()
  local rel

  if root and bufname:sub(1, #root) == root then
    rel = bufname:sub(#root + 2)
  else
    rel = vim.fn.fnamemodify(bufname, ":.")
  end

  local line = vim.api.nvim_win_get_cursor(0)[1]
  return string.format("%s:%d", rel, line)
end

Snacks.keymap.set("n", "<leader><tab>", ":edit #<cr>", { desc = "Switch to alternate file" })
Snacks.keymap.set("n", "<leader>'", function()
  local bufname = vim.api.nvim_buf_get_name(0)
  local dir = (bufname ~= "" and vim.fs.dirname(bufname)) or vim.loop.cwd()
  Snacks.terminal(nil, { cwd = dir })
end, { desc = "Terminal (buffer dir)" })
Snacks.keymap.set("n", "<leader>feU", ":Lazy update<cr>", { desc = "Update plugins" })
Snacks.keymap.set("n", "<leader>fyL", function()
  local text = filepath_with_line_project()
  set_clipboard(text)
end, { desc = "Yank file path + line (project)" })
Snacks.keymap.set("n", "<leader>fyl", function()
  local text = filepath_with_line_abs()
  set_clipboard(text)
end, { desc = "Yank file path + line (absolute)" })
Snacks.keymap.set({ "n", "x" }, "<leader>fs", ":write<cr>", { desc = "Save file" })
Snacks.keymap.set({ "n", "x" }, "<leader>ft", function()
  Snacks.explorer({ cwd = LazyVim.root() })
end, { desc = "Explorer Snacks (root dir)" })
Snacks.keymap.set({ "n", "x" }, "<leader>m==", function()
  LazyVim.format({ force = true })
end, { desc = "Format" })
Snacks.keymap.set("n", "<leader>p'", function()
  Snacks.terminal(nil, { cwd = LazyVim.root() })
end, { desc = "Terminal" })

Snacks.keymap.set("n", "<leader>ws", ":split | wincmd p<cr>", { desc = "Slit below" })
Snacks.keymap.set("n", "<leader>wv", ":vsplit | wincmd p<cr>", { desc = "Slit right" })
Snacks.keymap.set("n", "<leader>wS", ":split<cr>", { desc = "Slit below & focus" })
Snacks.keymap.set("n", "<leader>wV", ":vsplit<cr>", { desc = "Slit below & focus" })
Snacks.keymap.set("n", "<leader>wd", "<C-W>c", { desc = "Delete Window" })
Snacks.keymap.set("n", "<leader>wh", "<C-w>h", { desc = "Go to Left Window" })
Snacks.keymap.set("n", "<leader>wj", "<C-w>j", { desc = "Go to Lower Window" })
Snacks.keymap.set("n", "<leader>wk", "<C-w>k", { desc = "Go to Upper Window" })
Snacks.keymap.set("n", "<leader>wl", "<C-w>l", { desc = "Go to Right Window" })
