---@meta
--- Contract for the bookmarker controller.
---@class BookmarkerContract
---@field add fun(): ControllerAction
---@field remove fun(): ControllerAction
---@field list fun(): ControllerAction
