---@meta
--- Contract for the keymapper adapter.
---@class KeymapperAdapter
---@field format fun(map?: table): any
---@field register fun(map?: table): nil
---@field register_all fun(maps?: table): nil
---@field create_transient fun(opts?: table): any
