---@meta
--- Contract for the keymapper controller.
---@class KeymapperContract
---@field activate_transient fun(opts: { keys: string }): ControllerAction
---@field open fun(opts: { keys: string }): ControllerAction
