---@meta
--- Contract for the noter adapter.
---@class NoterAdapter
---@field new fun(): nil
---@field list fun(): nil
---@field dismiss fun(): nil
---@field find fun(): nil
---@field checkbox fun(action?: string): nil
---@field todo fun(action?: string): nil
---@field insert_heading fun(type?: string): nil
