---@meta
--- Output port for the bookmarker feature. Implemented by lua/infrastructure/adapters/bookmarker.lua.
---@class BookmarkerPort
---@field add fun(): nil
---@field remove fun(): nil
---@field remove_all fun(): nil
---@field list fun(): nil
