---@meta
--- Output port for the jumper feature. Implemented by lua/infrastructure/adapters/jumper.lua.
---@class JumperPort
---@field timer fun(options?: table): nil
---@field words fun(): nil
---@field lines fun(): nil
---@field remote fun(): nil
