--- Application-owned use-case registry (composition seam). Populated at bootstrap;
--- controllers read their use case from here
--- (require("application.ports.usecase_registry").<name>()) instead of importing
--- the use-case module directly. Mirrors application/ports/registry.lua.
--- No XUseCase types exist yet, so resolvers are typed loosely.
---@class UseCaseRegistry
---@field bookmarker fun(): table
---@field buffer fun(): table
---@field changer fun(): table
---@field chatbot fun(): table
---@field commander fun(): table
---@field commenter fun(): table
---@field completer fun(): table
---@field database fun(): table
---@field debugger fun(): table
---@field diagnostic fun(): table
---@field documentation fun(): table
---@field editor fun(): table
---@field file fun(): table
---@field fold fun(): table
---@field formatter fun(): table
---@field hover fun(): table
---@field jumper fun(): table
---@field layout fun(): table
---@field linenumber fun(): table
---@field lsp fun(): table
---@field notebook fun(): table
---@field noter fun(): table
---@field notification fun(): table
---@field outline fun(): table
---@field packager fun(): table
---@field pomodoro fun(): table
---@field quit fun(): table
---@field rest fun(): table
---@field screenshot fun(): table
---@field searcher fun(): table
---@field selector fun(): table
---@field statusline fun(): table
---@field terminal fun(): table
---@field tester fun(): table
---@field theme fun(): table
---@field todo fun(): table
---@field toggler fun(): table
---@field tree fun(): table
---@field versior fun(): table
---@field window fun(): table
---@field workspace fun(): table
---@field zen fun(): table
---@field zoom fun(): table
local M = {}

return M
