---@meta
--- Output port for the window feature. Implemented by lua/infrastructure/adapters/window.lua.
---@class WindowPort
---@field toggle fun(): nil
---@field go fun(direction?: string): nil
---@field move fun(direction?: string): nil
---@field move_far fun(direction?: string): nil
---@field go_to fun(number?: integer): nil
---@field close fun(): nil
---@field split fun(opts?: table): nil
---@field dedicate fun(): nil
---@field resize fun(opts: { axis: "width"|"height", delta: integer }): nil
---@field balance fun(): nil
---@field layout fun(opts: { count: integer }): nil
