--- Concrete controller registry. Implements ControllerRegistry and is injected
--- into the domain maps so the domain never imports controllers directly.
---@type ControllerRegistry
local M = {
  bookmarker = require("application.controllers.bookmarker"),
  buffer = require("application.controllers.buffer"),
  changer = require("application.controllers.changer"),
  chatbot = require("application.controllers.chatbot"),
  commander = require("application.controllers.commander"),
  commenter = require("application.controllers.commenter"),
  completer = require("application.controllers.completer"),
  database = require("application.controllers.database"),
  debugger = require("application.controllers.debugger"),
  diagnostic = require("application.controllers.diagnostic"),
  documentation = require("application.controllers.documentation"),
  editor = require("application.controllers.editor"),
  file = require("application.controllers.file"),
  fold = require("application.controllers.fold"),
  formatter = require("application.controllers.formatter"),
  hover = require("application.controllers.hover"),
  jumper = require("application.controllers.jumper"),
  layout = require("application.controllers.layout"),
  linenumber = require("application.controllers.linenumber"),
  lsp = require("application.controllers.lsp"),
  notebook = require("application.controllers.notebook"),
  noter = require("application.controllers.noter"),
  notification = require("application.controllers.notification"),
  outline = require("application.controllers.outline"),
  packager = require("application.controllers.packager"),
  pomodoro = require("application.controllers.pomodoro"),
  quit = require("application.controllers.quit"),
  rest = require("application.controllers.rest"),
  screenshot = require("application.controllers.screenshot"),
  searcher = require("application.controllers.searcher"),
  selector = require("application.controllers.selector"),
  statusline = require("application.controllers.statusline"),
  terminal = require("application.controllers.terminal"),
  tester = require("application.controllers.tester"),
  theme = require("application.controllers.theme"),
  todo = require("application.controllers.todo"),
  toggler = require("application.controllers.toggler"),
  tree = require("application.controllers.tree"),
  versior = require("application.controllers.versior"),
  window = require("application.controllers.window"),
  workspace = require("application.controllers.workspace"),
  zen = require("application.controllers.zen"),
  zoom = require("application.controllers.zoom"),
}

return M
